import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import Header from '../Components/Header'
import SmallCard from '../Components/SmallCard'
import MediumCard from '../Components/MediumCard'
import Banner from '../Components/Banner'
import LargeCard from '../Components/LargeCard'
import Footer from '../Components/Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ exploreData, exploreCardsData }) {
  return (
    <>
      <div className=''></div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

          {/* pull Data from Api */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, location, distance }) => (
              <SmallCard
                key={img}
                img={img}
                location={location}
                distance={distance} />
            ))}
          </div>
        </section>

        {/* pull Data from Api */}
        <section>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
            {exploreCardsData.map(({ img, title }) => (
              <MediumCard
                key={img}
                img={img}
                title={title} />
            ))}
          </div>
        </section>
        <LargeCard
          img={"https://a0.muscache.com/im/pictures/2da67c1c-0c61-4629-8798-1d4de1ac9291.jpg?im_w=1440"}
          title="The Greats Outdoors"
          desc='Wishlists curated by Airbnb'
          btnText='Get inspired'
        />
      </main>
      <Footer />
    </>
  )
}

export async function getStaticProps() {
  const data = await fetch("https://www.jsonkeeper.com/b/4G1G")
  const exploreData = await data.json();


  const CardsData = await fetch("https://www.jsonkeeper.com/b/VHHT")
  const exploreCardsData = await CardsData.json();

  return {
    props: {
      exploreData,
      exploreCardsData
    }, // will be passed to the page component as props
  }
}